deepseek:
  api-key: ${DEEPSEEK_API_KEY}
  base-url: https://api.deepseek.com/

logging:
  level:
    ir.dotin.llmproxyserver: DEBUG
    org.springframework.web: DEBUG
    reactor.netty: DEBUG

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000


rate-limit:
  requests-per-minute: 60
  requests-per-hour: 1000

server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: ${SSL_KEYSTORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: llmproxy
  http:
    port: 8080

spring:
  webflux:
    timeout:
      read: 30s
      write: 30s




